### ISSUE TITLE
Notices - Leagcy constructor

### ISSUE THREAD

**Issue by joncatalyst** [netspotau/moodle-mod_mediagallery#12]
Current plugin code, M2.9: With debug:Developer -  saving add-an-item & on edit (possibly elsewhere) I get:
Legacy constructor called, please update your code to call php5 constructor!
line 36 of /mod/mediagallery/classes/quickform/uploader_standard.php: call to debugging()
line 363 of /lib/pear/HTML/QuickForm/element.php: call to MoodleQuickForm_uploader_standard->MoodleQuickForm_uploader_standard()
line 171 of /lib/pear/HTML/QuickForm/input.php: call to HTML_QuickForm_element->onQuickFormEvent()
line 366 of /lib/pear/HTML/QuickForm/element.php: call to HTML_QuickForm_input->onQuickFormEvent()
line 171 of /lib/pear/HTML/QuickForm/input.php: call to HTML_QuickForm_element->onQuickFormEvent()
line 572 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm_input->onQuickFormEvent()
line 602 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm->_loadElement()
line 78 of /mod/mediagallery/item_form.php: call to HTML_QuickForm->addElement()
line 223 of /lib/formslib.php: call to mod_mediagallery_item_form->definition()
line 82 of /mod/mediagallery/item.php: call to moodleform->moodleform()

**Comment by aolley** [comment]
Curious. Moodle should be using the normal __construct that is available in that class in 2.9.

A quick fix for you might be to just remove the debugging statement in the /mod/mediagallery/classes/quickform/uploader_standard.php file - as the statement is definitely there as a warning to developers and isn't actually a cause of a real problem for you.
