### ISSUE TITLE
On hover image jumps around

### ISSUE THREAD

**Issue by tatikamsetti** [netspotau/moodle-mod_mediagallery#14]
When you hover on any image from the media gallery when the screen is resized to some extent, the images jump over when you hover on text/title of the image. Please see attached video for reference. Thanks.
[On_hover_image_jumps_around_1.zip](https://github.com/netspotau/moodle-mod_mediagallery/files/1794943/On_hover_image_jumps_around_1.zip)

**Comment by aolley** [comment]
I've addressed this by having the text appear in a tooltip rather than expanding the actively displayed text.
