### ISSUE TITLE
YouTube Media Galleries require users to allow unsafe content to be displayed

### ISSUE THREAD

**Issue by rlorenzo** [netspotau/moodle-mod_mediagallery#15]
Moodle Media Galleries can be designated as mode YouTube Gallery. However, when displaying a Media Collection pointing to a Media Gallery of mode YouTube Gallery, all browsers fail to play the videos unless unsafe content is allowed, despite the fact that all YouTube links are https://

![screenshot 2018-05-10 at 6 15 09 pm](https://user-images.githubusercontent.com/349765/40249254-417ed030-5a87-11e8-98e9-47d6bf98e087.png)

Is the fix as simple as changing this from http:// to https://?

https://github.com/netspotau/moodle-mod_mediagallery/blob/b9b507a5a92b6c7662e25ffee9a0afa85049c744/classes/item.php#L452

**Comment by aolley** [comment]
Given https links for those URLS are what youtube itself gives you when you grab a videos embed link (and using http promply is redirected) - then the fix is that simple. Thanks.
