### ISSUE TITLE
Failing Moodle 3.5 unit test

### ISSUE THREAD

**Issue by azrek** [netspotau/moodle-mod_mediagallery#17]
Hi,

Thank you for the plugin. We've recently installed it on a brand new Moodle 3.5 :

Moodle Version:
$version  = 2018051702.03; 
$release  = '3.5.2+ (Build: 20180920)';

Plugin Version:
$plugin->version   = 2018052500

But, the plugin is failing the privacy unit test with the following:

1) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - mediagallery (userid)

/var/www/moodle/privacy/tests/provider_test.php:274
/var/www/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

Would you be able to look into this?

Thank you in advance.

Ghada

**Comment by azrek** [comment]
Hi aolley,

Thank you so much for the quick turn around!!

Unfortunately, the unit test is failing because a language string is missing:

1) provider_testcase::test_metadata_provider with data set "mod_mediagallery" ('mod_mediagallery', 'mod_mediagallery\privacy\provider')
Expectation failed, debugging() was triggered.
Debugging: Invalid get_string() identifier: 'privacy:metadata:mediagallery:id' or component 'mod_mediagallery'. Perhaps you are missing $string['privacy:metadata:mediagallery:id'] = ''; in mod/mediagallery/lang/en/mediagallery.php?
* line 349 of /lib/classes/string_manager_standard.php: call to debugging()
* line 7103 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
* line 162 of /privacy/tests/provider_test.php: call to get_string()
* line ? of unknownfile: call to provider_testcase->test_metadata_provider()
* line 1071 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 939 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
* line 698 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 894 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 546 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
* line 195 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
* line 148 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
* line 53 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()

Failed asserting that 1 matches expected 0.

/var/www/moodle/lib/phpunit/classes/advanced_testcase.php:364
/var/www/moodle/privacy/tests/provider_test.php:163
/var/www/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

Should be quite an easy fix.

Thank you in advance.

Ghada

**Comment by aolley** [comment]
Copy/paste fail, c424fd80a75d792b6bec889814baac17be72d675 fixes it.

**Comment by azrek** [comment]
Hi aolley,

Thank you so much! All good!

Cheers,
Ghada
