### ISSUE TITLE
set_url missing

### ISSUE THREAD

**Issue by sleperf** [netspotau/moodle-mod_mediagallery#7]
In the view.php file a set_url is missing before use of $PAGE in line 103

**Comment by aolley** [comment]
All that happens there is adding to the navtree, as far as I'm aware, the url does not need to be set at that point - I could be wrong of course, what issue are you running into?

**Comment by aolley** [comment]
Scratch that. I can see it'd be a problem when trying to load it if the user wasn't already logged in.

**Comment by aolley** [comment]
I've added in the necessary calls to setup the cm and url for the page prior to doing stuff with the page nav and require_login:

https://github.com/netspotau/moodle-mod_mediagallery/commit/61066ae6bfca0f560bf50dc7e770d7efb163e22f

I've tested this on M2.9.4 successfully - accessing the page without being logged in properly, or logged in as guest, no longer results in a warning about the url not being set.

**Comment by sleperf** [comment]
Thanks for this quick fix.
