### ISSUE TITLE
Moodle 3.1 incompatibility 

### ISSUE THREAD

**Issue by rlorenzo** [netspotau/moodle-mod_mediagallery#8]
I am trying to run the Behat tests for Mediagallery in Moodle 3.1 (current master branch) and the Behat init script is failing with this error:

`Fatal error: Call to undefined method mod_mediagallery\search::get_config_var_name() in /Users/rex/Projects/mamp-moodle/admin/settings/plugins.php on line 502`

The problem is due to the new Global Search feature in https://tracker.moodle.org/browse/MDL-31989

Because the plugin has a class named "search" it is assuming that the plugin is offering to make its contents available to be indexed by global search, so it is looking for a method called get_config_var_name().

This will enable system admins to enable or disable this plugin's contents to be searchable.

The patch can be as easy as renaming the "search" class into something else or actually implementing support for Moodle's Global search.

In the meanwhile, the workaround is to use Moodle 3.0 or less.

**Comment by boofasten** [comment]
Hi rlorenzo - I was trying to make this plugin work in moodle 3.0 and it was not happening.  Is there anything in particular you did to make that happen?

**Comment by rlorenzo** [comment]
@boofasten I didn't have to do anything in particular. I just installed the latest code from their master branch: https://github.com/netspotau/moodle-mod_mediagallery/archive/master.zip

**Comment by nitro2010** [comment]
Hello,
For me, it doesn't working :(

**Comment by aolley** [comment]
I've pushed up a commit for the issue with the search class.

Another issue for 3.1 was the changes to the Tags API. I've also pushed a commit to address that.

**Comment by bgoodlin01** [comment]
Is there any reason why this issue hasn't been closed yet?  I'd like to install the code on our 3.1 server but I want to verify that this issue has been resolved.  Thanks!

**Comment by aolley** [comment]
Sorry you're right, I should've closed this.

I hope to find time this weekend to give the mediagallery plugins a final check and then flag them all for 3.1 on moodle.org (assuming they don't need fixes to work with 3.1).
